{% set name = "scikit-spatial" %}
{% set version = "6.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-spatial-{{ version }}.tar.gz
  sha256: f3f92bc5b6e29718b5f78779744c7d5fc848c0dd6301d58148de564dafe6dbd0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry >1,<2
  run:
    - python >=3.7
    - matplotlib-base >=3,<4
    - numpy >=1.20,<2

test:
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
