{% set name = "scikit-spatial" %}
{% set version = "9.0.1" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c56608088daae35b2caddee2b95e54d15bbfd48f0b760fa8a86817d0bcd0acc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3
    - numpy >=1.20
    - scipy >=1.9

test:
  requires:
    - python {{ python_min }}
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
