{% set name = "scikit-spatial" %}
{% set version = "7.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ccc85dda61fd1cb76c66cbd772e285fac40f593a0189852083af73598e7646f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry >1,<2
  run:
    - python >=3.7
    - matplotlib-base >=3,<4
    - numpy >=1.20,<2

test:
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
